[package]
name = "hello_lib"
version = "0.3.1"
edition = "2021"
repository = "https://github.com/endorlabs/TestingRustRepo/tree/main/hello_lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
world_lib = { path = "../world_lib" }