[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello_bin"
path = "src/main.rs"
test = false # we have no unit tests
doctest = false # and no doc tests

[dependencies]
hello_lib = { path = "../hello_lib" }